#ifndef SVGCOLORS_H
#define SVGCOLORS_H

#include <string>
#include <unordered_map>

namespace SVG {

enum class SvgColor {
    // Basic colors
    NONE,
    TRANSPARENT,
    
    // Reds
    ALICE_BLUE,
    ANTIQUE_WHITE,
    AQUA,
    AQUAMARINE,
    AZURE,
    BEIGE,
    BISQUE,
    BLACK,
    BLANCHED_ALMOND,
    BLUE,
    BLUE_VIOLET,
    BROWN,
    BURLY_WOOD,
    CADET_BLUE,
    CHARTREUSE,
    CHOCOLATE,
    CORAL,
    CORNFLOWER_BLUE,
    CORNSILK,
    CRIMSON,
    CYAN,
    DARK_BLUE,
    DARK_CYAN,
    DARK_GOLDENROD,
    DARK_GRAY,
    DARK_GREEN,
    DARK_GREY,
    DARK_KHAKI,
    DARK_MAGENTA,
    DARK_OLIVE_GREEN,
    DARK_ORANGE,
    DARK_ORCHID,
    DARK_RED,
    DARK_SALMON,
    DARK_SEA_GREEN,
    DARK_SLATE_BLUE,
    DARK_SLATE_GRAY,
    DARK_SLATE_GREY,
    DARK_TURQUOISE,
    DARK_VIOLET,
    DEEP_PINK,
    DEEP_SKY_BLUE,
    DIM_GRAY,
    DIM_GREY,
    DODGER_BLUE,
    FIREBRICK,
    FLORAL_WHITE,
    FOREST_GREEN,
    FUCHSIA,
    GAINSBORO,
    GHOST_WHITE,
    GOLD,
    GOLDENROD,
    GRAY,
    GREEN,
    GREEN_YELLOW,
    GREY,
    HONEYDEW,
    HOT_PINK,
    INDIAN_RED,
    INDIGO,
    IVORY,
    KHAKI,
    LAVENDER,
    LAVENDER_BLUSH,
    LAWN_GREEN,
    LEMON_CHIFFON,
    LIGHT_BLUE,
    LIGHT_CORAL,
    LIGHT_CYAN,
    LIGHT_GOLDENROD_YELLOW,
    LIGHT_GRAY,
    LIGHT_GREEN,
    LIGHT_GREY,
    LIGHT_PINK,
    LIGHT_SALMON,
    LIGHT_SEA_GREEN,
    LIGHT_SKY_BLUE,
    LIGHT_SLATE_GRAY,
    LIGHT_SLATE_GREY,
    LIGHT_STEEL_BLUE,
    LIGHT_YELLOW,
    LIME,
    LIME_GREEN,
    LINEN,
    MAGENTA,
    MAROON,
    MEDIUM_AQUAMARINE,
    MEDIUM_BLUE,
    MEDIUM_ORCHID,
    MEDIUM_PURPLE,
    MEDIUM_SEA_GREEN,
    MEDIUM_SLATE_BLUE,
    MEDIUM_SPRING_GREEN,
    MEDIUM_TURQUOISE,
    MEDIUM_VIOLET_RED,
    MIDNIGHT_BLUE,
    MINT_CREAM,
    MISTY_ROSE,
    MOCCASIN,
    NAVAJO_WHITE,
    NAVY,
    OLD_LACE,
    OLIVE,
    OLIVE_DRAB,
    ORANGE,
    ORANGE_RED,
    ORCHID,
    PALE_GOLDENROD,
    PALE_GREEN,
    PALE_TURQUOISE,
    PALE_VIOLET_RED,
    PAPAYA_WHIP,
    PEACH_PUFF,
    PERU,
    PINK,
    PLUM,
    POWDER_BLUE,
    PURPLE,
    REBECCA_PURPLE,
    RED,
    ROSY_BROWN,
    ROYAL_BLUE,
    SADDLE_BROWN,
    SALMON,
    SANDY_BROWN,
    SEA_GREEN,
    SEA_SHELL,
    SIENNA,
    SILVER,
    SKY_BLUE,
    SLATE_BLUE,
    SLATE_GRAY,
    SLATE_GREY,
    SNOW,
    SPRING_GREEN,
    STEEL_BLUE,
    TAN,
    TEAL,
    THISTLE,
    TOMATO,
    TURQUOISE,
    VIOLET,
    WHEAT,
    WHITE,
    WHITE_SMOKE,
    YELLOW,
    YELLOW_GREEN
};

class SvgColorConverter {
public:
    static std::string toString(SvgColor color) {
        static const std::unordered_map<SvgColor, std::string> colorMap = {
            // Basic colors
            {SvgColor::NONE, "none"},
            {SvgColor::TRANSPARENT, "transparent"},
            
            // Standard colors
            {SvgColor::ALICE_BLUE, "aliceblue"},
            {SvgColor::ANTIQUE_WHITE, "antiquewhite"},
            {SvgColor::AQUA, "aqua"},
            {SvgColor::AQUAMARINE, "aquamarine"},
            {SvgColor::AZURE, "azure"},
            {SvgColor::BEIGE, "beige"},
            {SvgColor::BISQUE, "bisque"},
            {SvgColor::BLACK, "black"},
            {SvgColor::BLANCHED_ALMOND, "blanchedalmond"},
            {SvgColor::BLUE, "blue"},
            {SvgColor::BLUE_VIOLET, "blueviolet"},
            {SvgColor::BROWN, "brown"},
            {SvgColor::BURLY_WOOD, "burlywood"},
            {SvgColor::CADET_BLUE, "cadetblue"},
            {SvgColor::CHARTREUSE, "chartreuse"},
            {SvgColor::CHOCOLATE, "chocolate"},
            {SvgColor::CORAL, "coral"},
            {SvgColor::CORNFLOWER_BLUE, "cornflowerblue"},
            {SvgColor::CORNSILK, "cornsilk"},
            {SvgColor::CRIMSON, "crimson"},
            {SvgColor::CYAN, "cyan"},
            {SvgColor::DARK_BLUE, "darkblue"},
            {SvgColor::DARK_CYAN, "darkcyan"},
            {SvgColor::DARK_GOLDENROD, "darkgoldenrod"},
            {SvgColor::DARK_GRAY, "darkgray"},
            {SvgColor::DARK_GREEN, "darkgreen"},
            {SvgColor::DARK_GREY, "darkgrey"},
            {SvgColor::DARK_KHAKI, "darkkhaki"},
            {SvgColor::DARK_MAGENTA, "darkmagenta"},
            {SvgColor::DARK_OLIVE_GREEN, "darkolivegreen"},
            {SvgColor::DARK_ORANGE, "darkorange"},
            {SvgColor::DARK_ORCHID, "darkorchid"},
            {SvgColor::DARK_RED, "darkred"},
            {SvgColor::DARK_SALMON, "darksalmon"},
            {SvgColor::DARK_SEA_GREEN, "darkseagreen"},
            {SvgColor::DARK_SLATE_BLUE, "darkslateblue"},
            {SvgColor::DARK_SLATE_GRAY, "darkslategray"},
            {SvgColor::DARK_SLATE_GREY, "darkslategrey"},
            {SvgColor::DARK_TURQUOISE, "darkturquoise"},
            {SvgColor::DARK_VIOLET, "darkviolet"},
            {SvgColor::DEEP_PINK, "deeppink"},
            {SvgColor::DEEP_SKY_BLUE, "deepskyblue"},
            {SvgColor::DIM_GRAY, "dimgray"},
            {SvgColor::DIM_GREY, "dimgrey"},
            {SvgColor::DODGER_BLUE, "dodgerblue"},
            {SvgColor::FIREBRICK, "firebrick"},
            {SvgColor::FLORAL_WHITE, "floralwhite"},
            {SvgColor::FOREST_GREEN, "forestgreen"},
            {SvgColor::FUCHSIA, "fuchsia"},
            {SvgColor::GAINSBORO, "gainsboro"},
            {SvgColor::GHOST_WHITE, "ghostwhite"},
            {SvgColor::GOLD, "gold"},
            {SvgColor::GOLDENROD, "goldenrod"},
            {SvgColor::GRAY, "gray"},
            {SvgColor::GREEN, "green"},
            {SvgColor::GREEN_YELLOW, "greenyellow"},
            {SvgColor::GREY, "grey"},
            {SvgColor::HONEYDEW, "honeydew"},
            {SvgColor::HOT_PINK, "hotpink"},
            {SvgColor::INDIAN_RED, "indianred"},
            {SvgColor::INDIGO, "indigo"},
            {SvgColor::IVORY, "ivory"},
            {SvgColor::KHAKI, "khaki"},
            {SvgColor::LAVENDER, "lavender"},
            {SvgColor::LAVENDER_BLUSH, "lavenderblush"},
            {SvgColor::LAWN_GREEN, "lawngreen"},
            {SvgColor::LEMON_CHIFFON, "lemonchiffon"},
            {SvgColor::LIGHT_BLUE, "lightblue"},
            {SvgColor::LIGHT_CORAL, "lightcoral"},
            {SvgColor::LIGHT_CYAN, "lightcyan"},
            {SvgColor::LIGHT_GOLDENROD_YELLOW, "lightgoldenrodyellow"},
            {SvgColor::LIGHT_GRAY, "lightgray"},
            {SvgColor::LIGHT_GREEN, "lightgreen"},
            {SvgColor::LIGHT_GREY, "lightgrey"},
            {SvgColor::LIGHT_PINK, "lightpink"},
            {SvgColor::LIGHT_SALMON, "lightsalmon"},
            {SvgColor::LIGHT_SEA_GREEN, "lightseagreen"},
            {SvgColor::LIGHT_SKY_BLUE, "lightskyblue"},
            {SvgColor::LIGHT_SLATE_GRAY, "lightslategray"},
            {SvgColor::LIGHT_SLATE_GREY, "lightslategrey"},
            {SvgColor::LIGHT_STEEL_BLUE, "lightsteelblue"},
            {SvgColor::LIGHT_YELLOW, "lightyellow"},
            {SvgColor::LIME, "lime"},
            {SvgColor::LIME_GREEN, "limegreen"},
            {SvgColor::LINEN, "linen"},
            {SvgColor::MAGENTA, "magenta"},
            {SvgColor::MAROON, "maroon"},
            {SvgColor::MEDIUM_AQUAMARINE, "mediumaquamarine"},
            {SvgColor::MEDIUM_BLUE, "mediumblue"},
            {SvgColor::MEDIUM_ORCHID, "mediumorchid"},
            {SvgColor::MEDIUM_PURPLE, "mediumpurple"},
            {SvgColor::MEDIUM_SEA_GREEN, "mediumseagreen"},
            {SvgColor::MEDIUM_SLATE_BLUE, "mediumslateblue"},
            {SvgColor::MEDIUM_SPRING_GREEN, "mediumspringgreen"},
            {SvgColor::MEDIUM_TURQUOISE, "mediumturquoise"},
            {SvgColor::MEDIUM_VIOLET_RED, "mediumvioletred"},
            {SvgColor::MIDNIGHT_BLUE, "midnightblue"},
            {SvgColor::MINT_CREAM, "mintcream"},
            {SvgColor::MISTY_ROSE, "mistyrose"},
            {SvgColor::MOCCASIN, "moccasin"},
            {SvgColor::NAVAJO_WHITE, "navajowhite"},
            {SvgColor::NAVY, "navy"},
            {SvgColor::OLD_LACE, "oldlace"},
            {SvgColor::OLIVE, "olive"},
            {SvgColor::OLIVE_DRAB, "olivedrab"},
            {SvgColor::ORANGE, "orange"},
            {SvgColor::ORANGE_RED, "orangered"},
            {SvgColor::ORCHID, "orchid"},
            {SvgColor::PALE_GOLDENROD, "palegoldenrod"},
            {SvgColor::PALE_GREEN, "palegreen"},
            {SvgColor::PALE_TURQUOISE, "paleturquoise"},
            {SvgColor::PALE_VIOLET_RED, "palevioletred"},
            {SvgColor::PAPAYA_WHIP, "papayawhip"},
            {SvgColor::PEACH_PUFF, "peachpuff"},
            {SvgColor::PERU, "peru"},
            {SvgColor::PINK, "pink"},
            {SvgColor::PLUM, "plum"},
            {SvgColor::POWDER_BLUE, "powderblue"},
            {SvgColor::PURPLE, "purple"},
            {SvgColor::REBECCA_PURPLE, "rebeccapurple"},
            {SvgColor::RED, "red"},
            {SvgColor::ROSY_BROWN, "rosybrown"},
            {SvgColor::ROYAL_BLUE, "royalblue"},
            {SvgColor::SADDLE_BROWN, "saddlebrown"},
            {SvgColor::SALMON, "salmon"},
            {SvgColor::SANDY_BROWN, "sandybrown"},
            {SvgColor::SEA_GREEN, "seagreen"},
            {SvgColor::SEA_SHELL, "seashell"},
            {SvgColor::SIENNA, "sienna"},
            {SvgColor::SILVER, "silver"},
            {SvgColor::SKY_BLUE, "skyblue"},
            {SvgColor::SLATE_BLUE, "slateblue"},
            {SvgColor::SLATE_GRAY, "slategray"},
            {SvgColor::SLATE_GREY, "slategrey"},
            {SvgColor::SNOW, "snow"},
            {SvgColor::SPRING_GREEN, "springgreen"},
            {SvgColor::STEEL_BLUE, "steelblue"},
            {SvgColor::TAN, "tan"},
            {SvgColor::TEAL, "teal"},
            {SvgColor::THISTLE, "thistle"},
            {SvgColor::TOMATO, "tomato"},
            {SvgColor::TURQUOISE, "turquoise"},
            {SvgColor::VIOLET, "violet"},
            {SvgColor::WHEAT, "wheat"},
            {SvgColor::WHITE, "white"},
            {SvgColor::WHITE_SMOKE, "whitesmoke"},
            {SvgColor::YELLOW, "yellow"},
            {SvgColor::YELLOW_GREEN, "yellowgreen"}
        };

        auto it = colorMap.find(color);
        if (it != colorMap.end()) {
            return it->second;
        }
        return "black"; // fallback color
    }

    static SvgColor fromString(const std::string& colorName) {
        static const std::unordered_map<std::string, SvgColor> nameMap = {
            // Reverse mapping
            {"none", SvgColor::NONE},
            {"transparent", SvgColor::TRANSPARENT},
            {"aliceblue", SvgColor::ALICE_BLUE},
            {"antiquewhite", SvgColor::ANTIQUE_WHITE},
            {"aqua", SvgColor::AQUA},
            {"aquamarine", SvgColor::AQUAMARINE},
            {"azure", SvgColor::AZURE},
            {"beige", SvgColor::BEIGE},
            {"bisque", SvgColor::BISQUE},
            {"black", SvgColor::BLACK},
            {"blanchedalmond", SvgColor::BLANCHED_ALMOND},
            {"blue", SvgColor::BLUE},
            {"blueviolet", SvgColor::BLUE_VIOLET},
            {"brown", SvgColor::BROWN},
            {"burlywood", SvgColor::BURLY_WOOD},
            {"cadetblue", SvgColor::CADET_BLUE},
            {"chartreuse", SvgColor::CHARTREUSE},
            {"chocolate", SvgColor::CHOCOLATE},
            {"coral", SvgColor::CORAL},
            {"cornflowerblue", SvgColor::CORNFLOWER_BLUE},
            {"cornsilk", SvgColor::CORNSILK},
            {"crimson", SvgColor::CRIMSON},
            {"cyan", SvgColor::CYAN},
            {"darkblue", SvgColor::DARK_BLUE},
            {"darkcyan", SvgColor::DARK_CYAN},
            {"darkgoldenrod", SvgColor::DARK_GOLDENROD},
            {"darkgray", SvgColor::DARK_GRAY},
            {"darkgreen", SvgColor::DARK_GREEN},
            {"darkgrey", SvgColor::DARK_GREY},
            {"darkkhaki", SvgColor::DARK_KHAKI},
            {"darkmagenta", SvgColor::DARK_MAGENTA},
            {"darkolivegreen", SvgColor::DARK_OLIVE_GREEN},
            {"darkorange", SvgColor::DARK_ORANGE},
            {"darkorchid", SvgColor::DARK_ORCHID},
            {"darkred", SvgColor::DARK_RED},
            {"darksalmon", SvgColor::DARK_SALMON},
            {"darkseagreen", SvgColor::DARK_SEA_GREEN},
            {"darkslateblue", SvgColor::DARK_SLATE_BLUE},
            {"darkslategray", SvgColor::DARK_SLATE_GRAY},
            {"darkslategrey", SvgColor::DARK_SLATE_GREY},
            {"darkturquoise", SvgColor::DARK_TURQUOISE},
            {"darkviolet", SvgColor::DARK_VIOLET},
            {"deeppink", SvgColor::DEEP_PINK},
            {"deepskyblue", SvgColor::DEEP_SKY_BLUE},
            {"dimgray", SvgColor::DIM_GRAY},
            {"dimgrey", SvgColor::DIM_GREY},
            {"dodgerblue", SvgColor::DODGER_BLUE},
            {"firebrick", SvgColor::FIREBRICK},
            {"floralwhite", SvgColor::FLORAL_WHITE},
            {"forestgreen", SvgColor::FOREST_GREEN},
            {"fuchsia", SvgColor::FUCHSIA},
            {"gainsboro", SvgColor::GAINSBORO},
            {"ghostwhite", SvgColor::GHOST_WHITE},
            {"gold", SvgColor::GOLD},
            {"goldenrod", SvgColor::GOLDENROD},
            {"gray", SvgColor::GRAY},
            {"green", SvgColor::GREEN},
            {"greenyellow", SvgColor::GREEN_YELLOW},
            {"grey", SvgColor::GREY},
            {"honeydew", SvgColor::HONEYDEW},
            {"hotpink", SvgColor::HOT_PINK},
            {"indianred", SvgColor::INDIAN_RED},
            {"indigo", SvgColor::INDIGO},
            {"ivory", SvgColor::IVORY},
            {"khaki", SvgColor::KHAKI},
            {"lavender", SvgColor::LAVENDER},
            {"lavenderblush", SvgColor::LAVENDER_BLUSH},
            {"lawngreen", SvgColor::LAWN_GREEN},
            {"lemonchiffon", SvgColor::LEMON_CHIFFON},
            {"lightblue", SvgColor::LIGHT_BLUE},
            {"lightcoral", SvgColor::LIGHT_CORAL},
            {"lightcyan", SvgColor::LIGHT_CYAN},
            {"lightgoldenrodyellow", SvgColor::LIGHT_GOLDENROD_YELLOW},
            {"lightgray", SvgColor::LIGHT_GRAY},
            {"lightgreen", SvgColor::LIGHT_GREEN},
            {"lightgrey", SvgColor::LIGHT_GREY},
            {"lightpink", SvgColor::LIGHT_PINK},
            {"lightsalmon", SvgColor::LIGHT_SALMON},
            {"lightseagreen", SvgColor::LIGHT_SEA_GREEN},
            {"lightskyblue", SvgColor::LIGHT_SKY_BLUE},
            {"lightslategray", SvgColor::LIGHT_SLATE_GRAY},
            {"lightslategrey", SvgColor::LIGHT_SLATE_GREY},
            {"lightsteelblue", SvgColor::LIGHT_STEEL_BLUE},
            {"lightyellow", SvgColor::LIGHT_YELLOW},
            {"lime", SvgColor::LIME},
            {"limegreen", SvgColor::LIME_GREEN},
            {"linen", SvgColor::LINEN},
            {"magenta", SvgColor::MAGENTA},
            {"maroon", SvgColor::MAROON},
            {"mediumaquamarine", SvgColor::MEDIUM_AQUAMARINE},
            {"mediumblue", SvgColor::MEDIUM_BLUE},
            {"mediumorchid", SvgColor::MEDIUM_ORCHID},
            {"mediumpurple", SvgColor::MEDIUM_PURPLE},
            {"mediumseagreen", SvgColor::MEDIUM_SEA_GREEN},
            {"mediumslateblue", SvgColor::MEDIUM_SLATE_BLUE},
            {"mediumspringgreen", SvgColor::MEDIUM_SPRING_GREEN},
            {"mediumturquoise", SvgColor::MEDIUM_TURQUOISE},
            {"mediumvioletred", SvgColor::MEDIUM_VIOLET_RED},
            {"midnightblue", SvgColor::MIDNIGHT_BLUE},
            {"mintcream", SvgColor::MINT_CREAM},
            {"mistyrose", SvgColor::MISTY_ROSE},
            {"moccasin", SvgColor::MOCCASIN},
            {"navajowhite", SvgColor::NAVAJO_WHITE},
            {"navy", SvgColor::NAVY},
            {"oldlace", SvgColor::OLD_LACE},
            {"olive", SvgColor::OLIVE},
            {"olivedrab", SvgColor::OLIVE_DRAB},
            {"orange", SvgColor::ORANGE},
            {"orangered", SvgColor::ORANGE_RED},
            {"orchid", SvgColor::ORCHID},
            {"palegoldenrod", SvgColor::PALE_GOLDENROD},
            {"palegreen", SvgColor::PALE_GREEN},
            {"paleturquoise", SvgColor::PALE_TURQUOISE},
            {"palevioletred", SvgColor::PALE_VIOLET_RED},
            {"papayawhip", SvgColor::PAPAYA_WHIP},
            {"peachpuff", SvgColor::PEACH_PUFF},
            {"peru", SvgColor::PERU},
            {"pink", SvgColor::PINK},
            {"plum", SvgColor::PLUM},
            {"powderblue", SvgColor::POWDER_BLUE},
            {"purple", SvgColor::PURPLE},
            {"rebeccapurple", SvgColor::REBECCA_PURPLE},
            {"red", SvgColor::RED},
            {"rosybrown", SvgColor::ROSY_BROWN},
            {"royalblue", SvgColor::ROYAL_BLUE},
            {"saddlebrown", SvgColor::SADDLE_BROWN},
            {"salmon", SvgColor::SALMON},
            {"sandybrown", SvgColor::SANDY_BROWN},
            {"seagreen", SvgColor::SEA_GREEN},
            {"seashell", SvgColor::SEA_SHELL},
            {"sienna", SvgColor::SIENNA},
            {"silver", SvgColor::SILVER},
            {"skyblue", SvgColor::SKY_BLUE},
            {"slateblue", SvgColor::SLATE_BLUE},
            {"slategray", SvgColor::SLATE_GRAY},
            {"slategrey", SvgColor::SLATE_GREY},
            {"snow", SvgColor::SNOW},
            {"springgreen", SvgColor::SPRING_GREEN},
            {"steelblue", SvgColor::STEEL_BLUE},
            {"tan", SvgColor::TAN},
            {"teal", SvgColor::TEAL},
            {"thistle", SvgColor::THISTLE},
            {"tomato", SvgColor::TOMATO},
            {"turquoise", SvgColor::TURQUOISE},
            {"violet", SvgColor::VIOLET},
            {"wheat", SvgColor::WHEAT},
            {"white", SvgColor::WHITE},
            {"whitesmoke", SvgColor::WHITE_SMOKE},
            {"yellow", SvgColor::YELLOW},
            {"yellowgreen", SvgColor::YELLOW_GREEN}
        };

        std::string lowerName = colorName;
        // Convert to lowercase for case-insensitive comparison
        for (char& c : lowerName) {
            c = std::tolower(c);
        }

        auto it = nameMap.find(lowerName);
        if (it != nameMap.end()) {
            return it->second;
        }
        return SvgColor::BLACK; // fallback color
    }
};

} // namespace SVG

#endif // SVGCOLORS_H